### ISSUE TITLE
Prompt fails in GitBash

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neo-sharp#513]
Running NeoSharp in Git Bash is impossible. It throws an exception
`
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_CursorLeft()
   at NeoSharp.Application.Client.ConsoleHandler.GetCursorPosition(Int32& x, Int32& y)
`

**Comment by shargon** [comment]
It's like if `Cursor.Left` doesn't work
